ETHIOPIAN_UNIVERSITIES = [
    "Addis Ababa University",
    "Adama Science and Technology University",
    "Addis Ababa Science and Technology University",
    "Adigrat University",
    "Adama University",
    "Ambo University",
    "Arba Minch University",
    "Assosa University",
    "Axum University",
    "Bahir Dar University",
    "Bule Hora University",
    "Debre Berhan University",
    "Debre Markos University",
    "Debre Tabor University",
    "Dire Dawa University",
    "Dilla University",
    "Ethiopian Civil Service University",
    "Gondar University",
    "Haramaya University",
    "Hawassa University",
    "Jimma University",
    "Jigjiga University",
    "Madda Walabu University",
    "Mekelle University",
    "Mizan Tepi University",
    "Rift Valley University",
    "Semera University",
    "Unity University",
    "Wachemo University",
    "Wolaita Sodo University",
    "Wollega University",
    "Wollo University",
    "Woldia University",
    "Wolkite University"
] 